create extension if not exists pg_trgm with schema public;

create table public.widgets (
	id bigint generated by default as identity primary key,
	name text not null,
	created_at timestamptz not null default now()
);

create index widgets_name_trgm_idx
	on public.widgets using gin (name public.gin_trgm_ops);

insert into storage.buckets (id, name, public)
values ('fixture-assets', 'fixture-assets', false);
