alter table public.widgets add column description text;

create table public.profiles (
	id uuid primary key references auth.users (id),
	display_name text not null,
	avatar_path text
);

create table public.food_compatibility_feedback (
	id bigint generated by default as identity primary key,
	decision text not null,
	reviewed_by uuid not null references auth.users (id)
);

create function public.preserve_review_history()
returns trigger
language plpgsql
as $$
begin
	if old.reviewed_by is distinct from new.reviewed_by then
		raise exception 'Food-warning decisions are immutable';
	end if;
	return new;
end
$$;

create trigger preserve_review_history
before update on public.food_compatibility_feedback
for each row execute function public.preserve_review_history();
