create table public.widgets (
	id bigint generated by default as identity primary key,
	name text not null,
	created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values ('fixture-assets', 'fixture-assets', false);
