/** Render reviewed local OAuth declarations into the disposable Supabase runtime. */

const escapePattern = (value) =>
  value.replaceAll(/[.*+?^${}()|[\]\\]/gu, "\\$&");

const LEGACY_PROVIDER_KEYS = new Set([
  "client_id",
  "email_optional",
  "enabled",
  "redirect_uri",
  "secret",
  "skip_nonce_check",
]);
const SAFE_BOOLEAN_PROVIDER_KEYS = new Set([
  "email_optional",
  "skip_nonce_check",
]);

const readTomlSections = (source) => {
  const lines = source.split("\n");
  const sections = [];
  for (let index = 0; index < lines.length; index += 1) {
    const match = /^\s*\[([^\]]+)\]\s*(?:#.*)?$/u.exec(lines[index]);
    if (!match) continue;
    if (sections.length) sections.at(-1).end = index;
    sections.push({ name: match[1], start: index, end: lines.length });
  }
  return { lines, sections };
};

const validateLegacyProviderSection = ({ lines, section, provider }) => {
  const seen = new Set();
  for (const line of lines.slice(section.start + 1, section.end)) {
    if (!line.trim() || /^\s*#/u.test(line)) continue;
    const assignment = /^\s*([A-Za-z0-9_]+)\s*=/u.exec(line);
    if (!assignment || !LEGACY_PROVIDER_KEYS.has(assignment[1])) {
      throw new Error(
        `The local Supabase template auth.external.${provider.name} section contains an unsupported setting. Rehearsal left the tracked template unchanged.`,
      );
    }
    const key = assignment[1];
    if (seen.has(key)) {
      throw new Error(
        `The local Supabase template auth.external.${provider.name} section contains duplicate ${key} settings.`,
      );
    }
    seen.add(key);
    if (
      SAFE_BOOLEAN_PROVIDER_KEYS.has(key) &&
      !new RegExp(
        `^\\s*${escapePattern(key)}\\s*=\\s*${
          key === "skip_nonce_check"
            ? (provider.skipNonceCheck ?? false)
            : (provider.emailOptional ?? false)
        }\\s*(?:#.*)?$`,
        "u",
      ).test(line)
    ) {
      throw new Error(
        `The local Supabase template auth.external.${provider.name}.${key} setting must match its explicit declarative authentication option before Rehearsal can replace the legacy provider in its disposable runtime copy.`,
      );
    }
  }
};

export const inspectSupabaseAuthenticationProviderTransition = ({
  source,
  authentication,
}) => {
  if (!authentication) return Object.freeze({ replacedProviders: [] });
  const { lines, sections } = readTomlSections(source);
  const replacementSections = [];
  for (const provider of authentication.providers) {
    const sectionName = `auth.external.${provider.name}`;
    const nested = sections.filter((section) =>
      section.name.startsWith(`${sectionName}.`),
    );
    if (nested.length) {
      throw new Error(
        `The local Supabase template contains unsupported nested ${sectionName} configuration. Rehearsal left the tracked template unchanged.`,
      );
    }
    const matching = sections.filter((section) => section.name === sectionName);
    if (matching.length > 1) {
      throw new Error(
        `The local Supabase template declares ${sectionName} more than once.`,
      );
    }
    if (matching.length === 1) {
      validateLegacyProviderSection({
        lines,
        section: matching[0],
        provider,
      });
      replacementSections.push({ ...matching[0], provider: provider.name });
    }
  }
  return Object.freeze({
    replacedProviders: Object.freeze(
      replacementSections.map(({ provider }) => provider),
    ),
    replacementSections: Object.freeze(replacementSections),
  });
};

export const renderSupabaseAuthenticationProviders = ({
  authentication,
  apiPort,
}) => {
  if (!authentication) return "";
  return authentication.providers
    .map(
      (
        provider,
      ) => `# Generated by Rehearsal from config.supabase.authentication.
[auth.external.${provider.name}]
enabled = true
client_id = "env(${provider.clientIdEnvironmentVariable})"
secret = "env(${provider.clientSecretEnvironmentVariable})"
redirect_uri = "http://127.0.0.1:${apiPort}/auth/v1/callback"
${provider.skipNonceCheck ? "skip_nonce_check = true\n" : ""}${provider.emailOptional ? "email_optional = true\n" : ""}
`,
    )
    .join("\n");
};

const enableLocalSignup = (source) => {
  const lines = source.split("\n");
  let inAuth = false;
  let authSections = 0;
  let signupSettings = 0;
  const updated = lines.map((line) => {
    const section = /^\s*\[([^\]]+)\]\s*(?:#.*)?$/u.exec(line);
    if (section) {
      inAuth = section[1] === "auth";
      if (inAuth) authSections += 1;
      return line;
    }
    if (!inAuth || !/^\s*enable_signup\s*=/u.test(line)) return line;
    signupSettings += 1;
    const comment = line.match(/\s+#.*$/u)?.[0] ?? "";
    return `enable_signup = true${comment}`;
  });
  if (authSections !== 1 || signupSettings !== 1) {
    throw new Error(
      "The local Supabase template must declare exactly one [auth] section with one enable_signup setting before Rehearsal can configure OAuth.",
    );
  }
  return updated.join("\n");
};

export const applySupabaseAuthenticationProviders = ({
  source,
  authentication,
  apiPort,
}) => {
  if (!authentication) return source;
  const transition = inspectSupabaseAuthenticationProviderTransition({
    source,
    authentication,
  });
  const { lines } = readTomlSections(source);
  const replacedIndexes = new Set(
    transition.replacementSections.flatMap((section) =>
      Array.from(
        { length: section.end - section.start },
        (_, offset) => section.start + offset,
      ),
    ),
  );
  const transitionedSource = lines
    .filter((_, index) => !replacedIndexes.has(index))
    .join("\n");
  const runtimeSource = enableLocalSignup(transitionedSource);
  const separator = runtimeSource.endsWith("\n") ? "\n" : "\n\n";
  return `${runtimeSource}${separator}${renderSupabaseAuthenticationProviders({ authentication, apiPort })}`;
};
