import { mkdtemp, readlink, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import {
  removeBaselineArtifactRoot,
  verifyActiveBaseline,
} from "../../../src/baseline/artifact.mjs";
import { refreshPostgresqlBaseline } from "../../../src/source/baseline.mjs";
import { sourceTargetFingerprint } from "../../../src/source/access.mjs";

const roots = [];
const connectionString =
  "postgresql://rehearsal_reader:reader-secret@127.0.0.1:55432/source_fixture";
const ledgerRows = [
  {
    version: "20260101000000",
    name: "create_widgets",
    statements: [
      "create table public.widgets (\n  id bigint generated by default as identity primary key,\n  name text not null,\n  created_at timestamptz not null default now()\n)",
    ],
  },
];
const sourcePolicy = {
  accessVersion: 1,
  targetFingerprint: sourceTargetFingerprint(connectionString),
  administratorEnvironmentVariable: "REHEARSAL_SOURCE_ADMIN_URL",
  reader: {
    role: "rehearsal_fixture_reader",
    ownerRole: "rehearsal_fixture_owner",
    credentialFile: ".rehearsal/secrets/source-reader.env",
    validForMinutes: 30,
  },
  exportSchema: "rehearsal_export_fixture",
  migrationLedger: {
    schema: "supabase_migrations",
    table: "schema_migrations",
    versionColumn: "version",
    nameColumn: "name",
    statementsColumn: "statements",
  },
  relations: [
    {
      source: { schema: "public", table: "widgets" },
      view: "widgets",
      targetTable: "widgets",
      columns: ["id", "name", "created_at"],
      orderBy: ["id"],
      rowScope: { kind: "approved-public" },
    },
  ],
};
const sourceAccessReceipt = {
  targetFingerprint: sourcePolicy.targetFingerprint,
  planDigest: "a".repeat(64),
  expiresAt: "2099-01-01T00:00:00.000Z",
  exportSchema: sourcePolicy.exportSchema,
  views: sourcePolicy.relations.map((relation) => relation.view).sort(),
  relations: sourcePolicy.relations.map((relation) => ({
    ...relation.source,
    columns: relation.columns,
  })),
  migrationLedger: sourcePolicy.migrationLedger,
  readerRole: sourcePolicy.reader.role,
  ownerRole: sourcePolicy.reader.ownerRole,
};
const privacyPolicy = {
  policyVersion: 2,
  migrationCutoff: "20260101000000",
  tables: [
    {
      name: "widgets",
      sourceRows: "STREAM AND SANITIZE",
      columns: [
        {
          name: "id",
          action: "KEEP",
          generated: "NEVER",
          identity: "YES",
          foreignKey: null,
        },
        {
          name: "name",
          action: "REPLACE",
          recipe: { kind: "constant", value: "Safe widget" },
          generated: "NEVER",
          identity: "NO",
          foreignKey: null,
        },
        {
          name: "created_at",
          action: "DERIVE",
          recipe: { kind: "date-shift", days: 7 },
          generated: "NEVER",
          identity: "NO",
          foreignKey: null,
        },
      ],
    },
  ],
};

const schemaRows = [
  {
    name: "id",
    data_type: "bigint",
    udt_name: "int8",
    is_nullable: "NO",
    is_generated: "NEVER",
    is_identity: "YES",
    ordinal_position: 1,
  },
  {
    name: "name",
    data_type: "text",
    udt_name: "text",
    is_nullable: "NO",
    is_generated: "NEVER",
    is_identity: "NO",
    ordinal_position: 2,
  },
  {
    name: "created_at",
    data_type: "timestamp with time zone",
    udt_name: "timestamptz",
    is_nullable: "NO",
    is_generated: "NEVER",
    is_identity: "NO",
    ordinal_position: 3,
  },
];

const fakeClient = ({
  observer = false,
  drift = false,
  failDuringFetch = false,
} = {}) => {
  let fetched = false;
  return {
    async connect() {},
    async end() {},
    async query(sql) {
      if (sql.includes("as version") && sql.includes("schema_migrations")) {
        return {
          rows: drift
            ? [{ ...ledgerRows[0], name: "changed_during_refresh" }]
            : ledgerRows,
        };
      }
      if (sql.includes("information_schema.columns"))
        return { rows: schemaRows };
      if (sql.includes("pg_column_size"))
        return { rows: [{ rows: "2", bytes: "256" }] };
      if (sql.startsWith("fetch forward")) {
        if (failDuringFetch) throw new Error("synthetic interrupted stream");
        if (observer || fetched) return { rows: [] };
        fetched = true;
        return {
          rows: [
            {
              id: 1,
              name: "Secret one",
              created_at: "2026-01-01T00:00:00.000Z",
            },
            {
              id: 2,
              name: "Secret two",
              created_at: "2026-01-02T00:00:00.000Z",
            },
          ],
        };
      }
      return { rows: [] };
    },
  };
};

afterEach(async () => {
  await Promise.all(
    roots.splice(0).map(async (root) => {
      await removeBaselineArtifactRoot({
        artifactRoot: join(root, ".rehearsal"),
      }).catch(() => undefined);
      await rm(root, { recursive: true });
    }),
  );
});

describe("coherent source baseline refresh", () => {
  it("rejects a receipt for a different export surface", async () => {
    const root = await mkdtemp(join(tmpdir(), "rehearsal-source-baseline-"));
    roots.push(root);
    await expect(
      refreshPostgresqlBaseline({
        connectionString,
        sourcePolicy,
        sourceAccessReceipt: {
          ...sourceAccessReceipt,
          views: ["unreviewed_view"],
        },
        privacyPolicyBytes: Buffer.from(`${JSON.stringify(privacyPolicy)}\n`),
        privacyKey: Buffer.alloc(32, 4),
        artifactRoot: join(root, ".rehearsal"),
        migrationDirectory: join(
          process.cwd(),
          "tests/fixtures/postgresql-project/database/migrations",
        ),
        availableBytes: 1024 * 1024 * 1024,
        clientFactory: async () => fakeClient(),
      }),
    ).rejects.toThrow("missing, mismatched, or expired");
  });

  it("streams, sanitizes, stages, verifies, and atomically activates", async () => {
    const root = await mkdtemp(join(tmpdir(), "rehearsal-source-baseline-"));
    roots.push(root);
    const artifactRoot = join(root, ".rehearsal");
    const clients = [fakeClient(), fakeClient({ observer: true })];
    const result = await refreshPostgresqlBaseline({
      connectionString,
      sourcePolicy,
      sourceAccessReceipt,
      privacyPolicyBytes: Buffer.from(`${JSON.stringify(privacyPolicy)}\n`),
      privacyKey: Buffer.alloc(32, 4),
      artifactRoot,
      migrationDirectory: join(
        process.cwd(),
        "tests/fixtures/postgresql-project/database/migrations",
      ),
      availableBytes: 1024 * 1024 * 1024,
      clientFactory: async () => clients.shift(),
    });
    const manifest = await verifyActiveBaseline({ artifactRoot });
    expect(manifest.generationId).toBe(result.generationId);
    expect(manifest.rowCount).toBe(2);
    expect(manifest.privacyKeyFingerprint).toMatch(/^[a-f0-9]{64}$/u);
    expect(manifest.sourceSchemaSha256).toMatch(/^[a-f0-9]{64}$/u);
  });

  it("preserves the prior baseline when source evidence drifts", async () => {
    const root = await mkdtemp(join(tmpdir(), "rehearsal-source-baseline-"));
    roots.push(root);
    const artifactRoot = join(root, ".rehearsal");
    const common = {
      connectionString,
      sourcePolicy,
      sourceAccessReceipt,
      privacyPolicyBytes: Buffer.from(`${JSON.stringify(privacyPolicy)}\n`),
      privacyKey: Buffer.alloc(32, 4),
      artifactRoot,
      migrationDirectory: join(
        process.cwd(),
        "tests/fixtures/postgresql-project/database/migrations",
      ),
      availableBytes: 1024 * 1024 * 1024,
    };
    let clients = [fakeClient(), fakeClient({ observer: true })];
    await refreshPostgresqlBaseline({
      ...common,
      clientFactory: async () => clients.shift(),
    });
    const before = await readlink(join(artifactRoot, "current"));
    clients = [fakeClient(), fakeClient({ observer: true, drift: true })];
    await expect(
      refreshPostgresqlBaseline({
        ...common,
        clientFactory: async () => clients.shift(),
      }),
    ).rejects.toThrow("changed during baseline preparation");
    expect(await readlink(join(artifactRoot, "current"))).toBe(before);
  });

  it.each([
    ["low disk", { availableBytes: 1 }, "needs approximately"],
    ["interrupted stream", { failDuringFetch: true }, "interrupted stream"],
  ])(
    "preserves the prior baseline after %s",
    async (_label, failure, message) => {
      const root = await mkdtemp(join(tmpdir(), "rehearsal-source-baseline-"));
      roots.push(root);
      const artifactRoot = join(root, ".rehearsal");
      const common = {
        connectionString,
        sourcePolicy,
        sourceAccessReceipt,
        privacyPolicyBytes: Buffer.from(`${JSON.stringify(privacyPolicy)}\n`),
        privacyKey: Buffer.alloc(32, 4),
        artifactRoot,
        migrationDirectory: join(
          process.cwd(),
          "tests/fixtures/postgresql-project/database/migrations",
        ),
      };
      let clients = [fakeClient(), fakeClient({ observer: true })];
      await refreshPostgresqlBaseline({
        ...common,
        availableBytes: 1024 * 1024 * 1024,
        clientFactory: async () => clients.shift(),
      });
      const before = await readlink(join(artifactRoot, "current"));
      clients = [fakeClient({ failDuringFetch: failure.failDuringFetch })];
      await expect(
        refreshPostgresqlBaseline({
          ...common,
          availableBytes: failure.availableBytes ?? 1024 * 1024 * 1024,
          clientFactory: async () => clients.shift(),
        }),
      ).rejects.toThrow(message);
      expect(await readlink(join(artifactRoot, "current"))).toBe(before);
    },
  );
});
