/**
 * Purpose: Plan and apply conservative first-run Rehearsal scaffolding without
 * contacting hosted services or overwriting project-owned files.
 */

import { createConnection, createServer } from "node:net";
import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import {
  inspectDetectedProject,
  renderDetectedConfig,
  renderDetectedPostgresqlConfig,
} from "./configuration.mjs";
import { resolveRuntimeTarget } from "../runtime/runtime_target.mjs";

const CONFIG_PATH = "rehearsal.config.mjs";
const LOCAL_SUPABASE_CONFIG_PATH =
  "infrastructure/rehearsal/supabase/config.toml";
const GITIGNORE_PATH = ".gitignore";
const PORT_OFFSETS = Object.freeze({
  shadow: 0,
  api: 1,
  database: 2,
  studio: 3,
  smtp: 4,
  pooler: 9,
});

const pathExists = (path) =>
  access(path)
    .then(() => true)
    .catch((error) => {
      if (error?.code === "ENOENT") return false;
      throw error;
    });

const readOptionalFile = async (path) => {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") return null;
    throw error;
  }
};

const canConnectToPort = (port) =>
  new Promise((resolveAvailability) => {
    const socket = createConnection({ host: "127.0.0.1", port });
    const finish = (result) => {
      socket.destroy();
      resolveAvailability(result);
    };
    socket.setTimeout(500);
    socket.once("connect", () => finish(true));
    socket.once("error", () => finish(false));
    socket.once("timeout", () => finish(false));
  });

const canBindToPort = (port) =>
  new Promise((resolveAvailability) => {
    const server = createServer();
    server.unref();
    server.once("error", () => resolveAvailability(false));
    server.listen({ host: "127.0.0.1", port, exclusive: true }, () => {
      server.close(() => resolveAvailability(true));
    });
  });

export const isRehearsalPortAvailable = async (port) => {
  if (await canConnectToPort(port)) return false;
  return canBindToPort(port);
};

export const inspectRehearsalNodeRuntime = (
  version = process.versions.node,
) => {
  const major = Number.parseInt(String(version).split(".")[0], 10);
  return {
    version: String(version),
    major,
    supported: major === 24,
  };
};

export const assertSupportedRehearsalNodeRuntime = (
  version = process.versions.node,
) => {
  const runtime = inspectRehearsalNodeRuntime(version);
  if (!runtime.supported) {
    throw new Error(
      `Rehearsal setup requires Node.js 24; this shell is using Node.js ${runtime.version}. Switch to Node.js 24, then rerun setup. With nvm: nvm install 24 && nvm use 24.`,
    );
  }
  return runtime;
};

export const findAvailableRehearsalPorts = async ({
  isAvailable = isRehearsalPortAvailable,
} = {}) => {
  for (let base = 58_320; base <= 65_520; base += 20) {
    const entries = Object.entries(PORT_OFFSETS).map(([name, offset]) => [
      name,
      base + offset,
    ]);
    const availability = await Promise.all(
      entries.map(([, port]) => isAvailable(port)),
    );
    if (availability.every(Boolean)) return Object.fromEntries(entries);
  }
  throw new Error(
    "Rehearsal could not find an available local port block between 58320 and 65529.",
  );
};

const databaseMajorVersionFrom = (source) => {
  const match = /^\s*major_version\s*=\s*(\d+)\s*(?:#.*)?$/imu.exec(
    source ?? "",
  );
  return match ? Number(match[1]) : 17;
};

export const renderSafeLocalSupabaseConfig = ({
  projectId,
  applicationUrl,
  ports,
  databaseMajorVersion = 17,
}) => `# Generated by Rehearsal for a disposable, local-only runtime.
# Review project-specific Auth or Storage additions before enabling them here.
project_id = ${JSON.stringify(projectId)}

[api]
enabled = true
port = ${ports.api}
schemas = ["public"]
extra_search_path = ["public", "extensions"]

[db]
port = ${ports.database}
shadow_port = ${ports.shadow}
major_version = ${databaseMajorVersion}

[db.pooler]
enabled = false
port = ${ports.pooler}

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = false
sql_paths = []

[studio]
enabled = true
port = ${ports.studio}
api_url = "http://127.0.0.1"

[local_smtp]
enabled = false
port = ${ports.smtp}

[auth]
enabled = true
site_url = ${JSON.stringify(applicationUrl)}
enable_signup = false

[storage]
enabled = true

[realtime]
enabled = false

[edge_runtime]
enabled = false

[analytics]
enabled = false
`;

const appendGitignoreEntries = (source) => {
  const original = source ?? "";
  const lines = new Set(
    original
      .split(/\r?\n/u)
      .map((line) => line.trim())
      .filter(Boolean),
  );
  const entries = [".rehearsal/", ".env.rehearsal-service.local"];
  const missing = entries.filter(
    (entry) =>
      !lines.has(entry) &&
      !lines.has(`/${entry}`) &&
      !lines.has(entry.replace(/\/$/u, "")),
  );
  if (missing.length === 0) return original;
  const prefix =
    original && !original.endsWith("\n") ? `${original}\n` : original;
  const separator = prefix && !prefix.endsWith("\n\n") ? "\n" : "";
  return `${prefix}${separator}# Rehearsal local artifacts\n${missing.join("\n")}\n`;
};

const assertCreateTargetAvailable = async (file) => {
  if (file.action === "create" && (await pathExists(file.absolutePath))) {
    throw new Error(
      `Rehearsal setup will not overwrite the existing file at ${file.path}.`,
    );
  }
};

export const planRehearsalSetup = async ({
  projectRoot = process.cwd(),
  isPortAvailable,
  target = "supabase",
} = {}) => {
  const root = resolve(projectRoot);
  const runtimeTarget = resolveRuntimeTarget(target).id;
  const detected = await inspectDetectedProject({ projectRoot: root });
  const ports = await findAvailableRehearsalPorts({
    ...(isPortAvailable ? { isAvailable: isPortAvailable } : {}),
  });
  const applicationUrl = "http://localhost:5175";
  const projectId = `${detected.projectName}-rehearsal`;
  const sourceSupabaseConfig =
    runtimeTarget === "supabase"
      ? await readOptionalFile(join(root, "supabase/config.toml"))
      : null;
  const originalGitignore = await readOptionalFile(join(root, GITIGNORE_PATH));
  const nextGitignore = appendGitignoreEntries(originalGitignore);
  for (const path of [
    CONFIG_PATH,
    ...(runtimeTarget === "supabase" ? [LOCAL_SUPABASE_CONFIG_PATH] : []),
  ]) {
    if (await pathExists(join(root, path))) {
      throw new Error(
        `Rehearsal setup will not overwrite the existing file at ${path}.`,
      );
    }
  }
  const files = [
    {
      path: CONFIG_PATH,
      absolutePath: join(root, CONFIG_PATH),
      action: "create",
      mode: 0o600,
      content:
        runtimeTarget === "supabase"
          ? renderDetectedConfig(detected, {
              applicationUrl,
              ports,
            })
          : renderDetectedPostgresqlConfig(detected, {
              applicationUrl,
              databasePort: ports.database,
            }),
    },
    ...(runtimeTarget === "supabase"
      ? [
          {
            path: LOCAL_SUPABASE_CONFIG_PATH,
            absolutePath: join(root, LOCAL_SUPABASE_CONFIG_PATH),
            action: "create",
            mode: 0o600,
            content: renderSafeLocalSupabaseConfig({
              projectId,
              applicationUrl,
              ports,
              databaseMajorVersion:
                databaseMajorVersionFrom(sourceSupabaseConfig),
            }),
          },
        ]
      : []),
    {
      path: GITIGNORE_PATH,
      absolutePath: join(root, GITIGNORE_PATH),
      action:
        nextGitignore === (originalGitignore ?? "")
          ? "unchanged"
          : originalGitignore === null
            ? "create"
            : "update",
      mode: 0o644,
      originalContent: originalGitignore,
      content: nextGitignore,
    },
  ];
  return {
    projectRoot: root,
    project: detected.projectName,
    projectId,
    target: runtimeTarget,
    applicationUrl,
    detected,
    ports: runtimeTarget === "supabase" ? ports : { database: ports.database },
    isPortAvailable: isPortAvailable ?? isRehearsalPortAvailable,
    files,
    safety: [
      "hosted access remains disabled",
      runtimeTarget === "supabase"
        ? "the Supabase runtime binds to dedicated local ports"
        : "PostgreSQL binds only to a dedicated loopback port",
      ...(runtimeTarget === "supabase"
        ? [
            "external identity providers, realtime, edge functions, and analytics start disabled",
          ]
        : [
            "the runtime uses an already-installed official PostgreSQL image and never pulls implicitly",
          ]),
      "configuration files are never overwritten and .gitignore updates are concurrency-checked",
    ],
  };
};

export const applyRehearsalSetup = async (plan) => {
  assertSupportedRehearsalNodeRuntime();
  const unavailablePorts = (
    await Promise.all(
      Object.values(plan.ports).map(async (port) => ({
        port,
        available: await plan.isPortAvailable(port),
      })),
    )
  ).filter(({ available }) => !available);
  if (unavailablePorts.length) {
    throw new Error(
      `Rehearsal setup ports became occupied after the preview (${unavailablePorts.map(({ port }) => port).join(", ")}); rerun setup to choose another local port block.`,
    );
  }
  for (const file of plan.files) await assertCreateTargetAvailable(file);
  const gitignore = plan.files.find((file) => file.path === GITIGNORE_PATH);
  if (gitignore?.action === "update") {
    const current = await readOptionalFile(gitignore.absolutePath);
    if (current !== gitignore.originalContent) {
      throw new Error(
        ".gitignore changed after the setup preview; rerun rehearsal setup before writing.",
      );
    }
  }
  for (const file of plan.files.filter(
    (entry) => entry.action !== "unchanged",
  )) {
    await mkdir(dirname(file.absolutePath), { recursive: true, mode: 0o700 });
    await writeFile(file.absolutePath, file.content, {
      flag: file.action === "create" ? "wx" : "w",
      mode: file.mode,
    });
  }
  return {
    projectRoot: plan.projectRoot,
    files: plan.files.map((file) => ({
      path: relative(plan.projectRoot, file.absolutePath),
      action: file.action,
    })),
  };
};

export const summarizeRehearsalSetup = (plan, { mode }) => ({
  mode,
  project: plan.project,
  projectId: plan.projectId,
  target: plan.target,
  applicationUrl: plan.applicationUrl,
  detected: plan.detected,
  ports:
    plan.target === "supabase"
      ? {
          api: plan.ports.api,
          database: plan.ports.database,
          studio: plan.ports.studio,
        }
      : { database: plan.ports.database },
  files: plan.files.map((file) => ({ path: file.path, action: file.action })),
  safety: plan.safety,
  nextAction:
    mode === "written"
      ? "Review the generated commands and sanitization policy path, then run rehearsal doctor."
      : "Review this plan, then rerun rehearsal setup --write to create it.",
});
