create table public.widgets (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create schema blendcalc_api;

create table blendcalc_api.widgets (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);
