create table public.widgets (
	id bigint generated by default as identity primary key,
	name text not null,
	created_at timestamptz not null default now(),
	historical_bytes_were_changed boolean not null default true
);
